name: sonos_control_dart
version: 0.0.1
description: 'Dedicated media controls for sonos systems'

environment:
  sdk: '>=2.7.1 <3.0.0'

dependencies:
  redux: ^3.0.0
  over_react: ^3.8.0
  built_value: ^7.0.0
  built_collection: ^4.3.2
  socket_io_client: ^0.9.10

dev_dependencies:
  build_runner: ^1.7.1
  build_web_compilers: ^2.7.1
  built_value_generator: ^7.0.0
  react: ^5.1.1
  sass_builder: ^2.1.2